[theme]
primaryColor = "#08234d"    # Goud/Oker (voor knoppen en selecties)
backgroundColor = "#e78a8a" # Diep Teal (voor de achtergrond)
secondaryBackgroundColor = "#c51c1c" # Iets lichter blauw (voor de zijbalk)
textColor = "#ffffff"       # Wit (zodat tekst leesbaar is op donker)
font = "sans serif"
