[theme]
# PNB Rood - Voor knoppen, sliders en selecties
primaryColor = "#DD0000"

# Wit - De basis achtergrondkleur
backgroundColor = "#FFFFFF"

# PNB Licht Warmgrijs - Voor de zijbalk (Sidebar) en blokken
secondaryBackgroundColor = "#EAEDEE"

# PNB Zwart - Voor alle leestekst
textColor = "#1D1D1B"

# Font - De provincie gebruikt online vaak Arial of Futura, sans serif komt het dichtst in de buurt
font = "sans serif"